### ISSUE TITLE
[MECHANIC]: Anti-Gravity Ball

### ISSUE THREAD

**Issue by LouieMarcou** [Blue-Square-Legion/Keito-Yarn-Game#118]
### Description of what will be added or updated

This yarn ball has no gravity to it after you shoot; it floats around the air, but objects and yarn balls can affect it by knocking it towards the ground with force or trying to hit it in different directions while it has no gravity.

**Comment by TheRealVicere** [comment]
Done; camera rework necessary to prevent these from becoming impossible to see
