### ISSUE TITLE
[MECHANIC]: Ball Limit

### ISSUE THREAD

**Issue by LouieMarcou** [Blue-Square-Legion/Keito-Yarn-Game#14]
### Description of what will be added or updated

Give the player a certain amount yarn balls to summon before they run out. If they run out, they fail. 

### Additional Information

An object pool should be used for this. There should also be UI to show how many yarn balls they have left. The randomness for the color of the yarn ball should be removed. The player should receive the colors in a pattern like in Tetris.

**Comment by KallenXCC** [comment]
@LouieMarcou I like the idea, can we flesh it out a bit more? How many yarn balls do we think would be an ideal limit? What will happen when the limit is reached? e.g. The oldest yarn ball disappears, game over? Should all levels have the same color pattern?

**Comment by KallenXCC** [comment]
I'll start investigating the implementation. @LouieMarcou In the meantime, any additional testing/details you can give would be appreciated. For example, trying to clear the level with a certain number of yarn balls and seeing what numbers you think works better. Of course the color patterns are not yet implemented, so you'd have to arbitrarily throw some balls away that don't fit the pattern you're going for.

**Comment by LouieMarcou** [comment]
We can start with 30

**Comment by SurajSSingh** [comment]
While this task does not depend on it for implementation, Issue #11 will also need to be finished to allow proper testing within the game. I will bump that up in priority

**Comment by KallenXCC** [comment]
Implemented 30 ball limit, updated UI to dynamically show Game Over! or Level Complete! and dynamically update buttons to Play Again, Next Level, or Back to Main Menu. Added UI to show how many balls are left.  Added a time buffer between using last ball and "Game Over" to see if player can win.

**Comment by KallenXCC** [comment]
Changes merged in https://github.com/Blue-Square-Legion/Keito-Yarn-Game/pull/32
