### ISSUE TITLE
[LEVEL]: Puzzle Level Prototype

### ISSUE THREAD

**Issue by SurajSSingh** [Blue-Square-Legion/Keito-Yarn-Game#25]
### Description of what will be added or updated

Create a simple prototype level to try out interesting puzzle mechanics. This level should try out interesting way to play the game and provide an interesting challenge for the player to overcome.

### Description of the scene/level to be added or edited

Create a new prototype level in `TEST - Editor Only/<Your Name>`. **Don't** edit any current level scene, if you want to reuse a level, make a copy of it.

### Additional Information

Multiple people can take on this issue.

**Comment by KallenXCC** [comment]
#89 was merged
