### ISSUE TITLE
[MECHANIC]: Bi-directional timer

### ISSUE THREAD

**Issue by SurajSSingh** [Blue-Square-Legion/Keito-Yarn-Game#28]
### Description of what will be added or updated

Make the game timer run either as a count-up or a countdown. We should be able to toggle this option from the inspector. When counting up, you are allowed to assume unlimited time. When counting down, the inspector must allow inputing the amount of time the player has. For example, putting in a value of 300, might mean the player has 300 seconds (5 minutes) to complete the level. When the timer end, the game is over.

This will be used for the challenge mode of the game.

### Additional Information

Relavent Miro section: https://miro.com/app/board/uXjVK-U-Y5k=/?moveToWidget=3458764594485495215&cot=14

**Comment by KallenXCC** [comment]
#54 was merged
