### ISSUE TITLE
[MECHANIC]: Star rating system

### ISSUE THREAD

**Issue by SurajSSingh** [Blue-Square-Legion/Keito-Yarn-Game#29]
### Description of what will be added or updated

To provide better feedback on how quickly the player finished the level, we want to add a star system to show how well the player did. The current model is a 3-star system from 1 to 3 stars, with 3 being the best times and 1 being the most time. As of now, the stars will only be controlled by the time taken in the level.

_**STRETCH GOAL**: We also want to allow the game to store previous stars to eventually allow showing improvements in time (e.g., going from 1 star to 2 star). This can also, down the line, allow us to add achievements or collectables based on star system_

Currently to be used for the challenge mode, may be expanded to the general levels if feedback on the system is very positive.

### Additional Information

Miro: https://miro.com/app/board/uXjVK-U-Y5k=/?moveToWidget=3458764594485495215&cot=14

> Give players a score system based on how fast they complete a stage. 
> Example not actual numbers: 3 stars = 0s-30s , 2 stars = 31s-60s, 1 star = 61s-MaxTime

**Comment by KallenXCC** [comment]
- Save different times for each level
- Clean up/remove PlayerPref bestTime
- Create Star Rating for each level
- Create Star UI
- Added new font that prints stars ★☆☆ properly

**Comment by KallenXCC** [comment]
Branch merged in #36
