### ISSUE TITLE
[ART]: Fridge Model

### ISSUE THREAD

**Issue by SurajSSingh** [Blue-Square-Legion/Keito-Yarn-Game#38]
### Description of what will be added or updated

Fridge model by Austin, import .fbx model and associated textures.

### Additional Information

Trello Card: https://trello.com/c/Gz8T6ybo

**Comment by KallenXCC** [comment]
@seribeengton were you already working on this or was there some kind of blocker?

**Comment by KallenXCC** [comment]
#73 was merged
