### ISSUE TITLE
[BUG]: Extra escape button in settings for pause menu

### ISSUE THREAD

**Issue by SurajSSingh** [Blue-Square-Legion/Keito-Yarn-Game#44]
### Description of the bug

There is an extra escape button in the setting page of the pause menu (top left). When clicked, it does not do anything in game.

Image of bug:
<img width="1167" alt="Multiple Escape Buttons" src="https://github.com/user-attachments/assets/6fc55a69-6f79-4e5a-a5b3-b737b85cc229">

### Steps To Reproduce

1. Start game in any official scene (Tutorial, In-Game/Living Room, Kitchen)
2. Pause the game to bring up the pause menu
3. Click on the "settings" option
4. At the top left, you will see another escape button, which does not do anything when clicked
5. Top right escape button will close settings menu 

### Possible fix: 
Remove the unnecessary button from the settings prefab.

**Comment by KallenXCC** [comment]
#57 was merged
