### ISSUE TITLE
[BUG]: Tutorial NullReferenceException

### ISSUE THREAD

**Issue by KallenXCC** [Blue-Square-Legion/Keito-Yarn-Game#46]
### Description of the bug

NullReferenceException when playing the tutorial level which prevents any yarn balls from being thrown.
![nullRefBug](https://github.com/user-attachments/assets/0a1b4f55-6e30-4fa3-beff-e0e31dead684)

### Steps To Reproduce

1. Build and run the game from the latest develop version.
2. Play the tutorial level.
Expected behavior: Yarn balls can be thrown normally
Actual behavior: Yarn ball to throw doesn't exist (NullReferenceException)

### Possible fix:
Initialize the reference for Color List of the Game Manager in the Tutorial Scene, which was de-initialized when ColorSO was changed to YarnAttributeSO

**Comment by SurajSSingh** [comment]
Fixed with PR #47, which has been merge in.
