### ISSUE TITLE
[MECHANIC]: Yarn Ball Camera Focus

### ISSUE THREAD

**Issue by SurajSSingh** [Blue-Square-Legion/Keito-Yarn-Game#5]
### Description of what will be added or updated

Allow the player to focus on yarn balls that are in the level instead of just rotating around center of the level. This can allow the player to more easily line up the yarn ball shots.

Some constraints:
- Player should be able to swap focus between yarn balls with a single button. 
- Camera should not phase into the yarn ball regardless of size. 
- Camera may or may not move with the yarn ball, but it must always have yarn ball in focus (i.e., camera can be stationary but should still track the yarn ball's movement)
- Rotation should not be affected by switching.
- When yarn ball disappears (such as getting it to the cat) it should bring focus to something (either cat, another yarn ball, or back to center of level).

### Additional Information

Look at Prototype Yarn Camera scene (Assets/Scenes/TEST - Editor Only/Light with Blocks/PrototypeSingleYarnCamera.unity) for example of what could be done. This prototype was not pursued originally due to being confusing to players, but may be useful for allowing players to switch between balls for the puzzle version.

**Comment by KallenXCC** [comment]
Scrapping in favor of #94
