### ISSUE TITLE
[BUG]: Mass affects arc

### ISSUE THREAD

**Issue by LouieMarcou** [Blue-Square-Legion/Keito-Yarn-Game#50]
### Description of the bug

The mass of the ball effects the visual arc of the ball. If you were to toss a heavier ball it will always fall short of where you are aiming.

### Steps To Reproduce

1. Go to YarnBallAttributeTesting branch
2. Go to In Game Scene or Kitchen scene
3. In the ScriptableObjects folder find the yarn ball attributes and change the mass of the yarn balls
4. Run the scene and toss the yarn balls

**Comment by KallenXCC** [comment]
I think this is when we added yarn ball different attributes. I agree that it should not have this behavior. To be clear what we want to do is disable the different attributes for now so that all colors throw the same? @LouieMarcou

**Comment by LouieMarcou** [comment]
No we want the arc adjust for the mass of each ball

**Comment by KallenXCC** [comment]
Ok I'll look into it. Although imo the gameplay is more fun and intuitive when the balls are the same weight. Please take this into consideration.

**Comment by LouieMarcou** [comment]
Yeah the yarn balls have different masses isn't final. Frankly in my testing I wasn't really satisfied with how they were working out. After this and some testing we can make a final decision.

**Comment by KallenXCC** [comment]
#62  resolves this issue
