### ISSUE TITLE
[BUG]: Pause Screen Over

### ISSUE THREAD

**Issue by LouieMarcou** [Blue-Square-Legion/Keito-Yarn-Game#52]
### Description of the bug

You can pause the game during the game over screen when you lose. Might want to check if this happens when you win too.

### Steps To Reproduce

1. Go to YarnBallAttributeTesting branch
2. Go to in game scene or kitchen scene
3. Lose 
4. Press escape

**Comment by KallenXCC** [comment]
#59 was merged
