### ISSUE TITLE
[MECHANIC]: Red Ball Excessive Force

### ISSUE THREAD

**Issue by LouieMarcou** [Blue-Square-Legion/Keito-Yarn-Game#64]
### Description of what will be added or updated

Red Yarn ball with add a lot of force to any non red yarn ball it collides with after it is thrown but this effect will disappear as soon as it stops moving. The effect will not return if a yarn ball collides with it.

Just to be absolutely clear: This effect will only be active once the ball is thrown and will disappear forever once it stops moving.

**Comment by KallenXCC** [comment]
#72 #74 were merged
