### ISSUE TITLE
[MECHANIC]: C# Yarn Ball Effect Interface

### ISSUE THREAD

**Issue by LouieMarcou** [Blue-Square-Legion/Keito-Yarn-Game#67]
### Description of what will be added or updated

This is an interface that will have functions like "createEffect" and "applyEffect". There will be multiple yarn ball effect scripts that will implement this interface. Those scripts will be called by the yarn ball itself when an event happens like an onCollision event.

### Additional Information

Light's notes about it:
- Start with C# interface with common functionality for effects
- Multiple scripts with for each effect that implements the interface
- Have events for when effect is to be applied

**Comment by KallenXCC** [comment]
#68 was merged
