### ISSUE TITLE
[FEEDBACK]: Sticky Ball is hard to move

### ISSUE THREAD

**Issue by LouieMarcou** [Blue-Square-Legion/Keito-Yarn-Game#82]
### Provide your feedback

We got feedback that the green ball can be hard to move if too many yarn balls are attached. This kind of the point of the sticky ball but maybe we should lower the mass of each yarn ball that is attached to the sticky ball. That should make it a bit easier for the sticky ball to move.

While the yarn balls are attached to the sticky ball they will have a slightly lower mass. When they get detached their mass will return to normal.

**Comment by KallenXCC** [comment]
#91 was merged
