### ISSUE TITLE
[BUG]: Yarn stuck inside Green Ball

### ISSUE THREAD

**Issue by LouieMarcou** [Blue-Square-Legion/Keito-Yarn-Game#83]
### Description of the bug

If the green yarn ball is big enough and had other yarn balls attached beforehand, they will be stuck inside. This could changed or left as it is.

### Steps To Reproduce

1. Go to in game scene
2. Attach several yarn to a green ball
3. Combine the green ball enough to see the bug happen

**Comment by KallenXCC** [comment]
I think we can leave this as is, the large yarn balls are of higher consequence and absorbing the smaller yarn balls is an acceptable result imo. Fixing this issue is non-trivial and entirely necessary. We could revisit it if a lot of people are complaining about it.
