### ISSUE TITLE
[BUG]: Cyan ball auto merge

### ISSUE THREAD

**Issue by KallenXCC** [Blue-Square-Legion/Keito-Yarn-Game#93]
### Description of the bug

Occasionally, when a differently colored ball is launched at a stationary cyan ball, the balls will immediately merge instead of the launched ball getting knocked back while its color changes to cyan.

### Steps To Reproduce

1. Launch a different colored ball at a stationary cyan ball with the color change effect.

Expected Result: The stationary ball changes color and gets knocked back
Actual Result: The stationary ball changes color and merges immediately with the cyan ball without having a chance to get knocked back first

### Additional Information

#81 #87

**Comment by TheRealVicere** [comment]
I think this only occurs if the balls touch twice, as I've tried to reproduce the bug several times but it only occurred once. I'll keep looking at it though!
